{{- if .Values.profiseeRunTime.isPaaS }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns-custom
    namespace: kube-system
data:
  ingress.server: |2
      profiseecloud.com:53 {
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts {
          10.58.255.1 profiseecloud.com
          fallthrough
        }
      }
{{- end }}