{{- if not .Values.cloud.azure.useKeyVault -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-oidc-secret
data:
  ProfiseeOidcClientSecret: {{.Values.profiseeRunTime.oidc.clientSecret | b64enc | quote}}
{{- end }}