controller:
  ingressClass:
    name: nginx
    create: true
  enableCustomResources: false
  nginxplus: false
  enableSnippets: true
  config:
    entries:
      server-tokens: "false"
  defaultTLS:
    secret: profisee/profisee-tls-ingress
  nodeSelector:
    kubernetes.io/os: linux
  replicaCount: 1
  service:
    type: LoadBalancer

